{% set name = "sphinx-multitoc-numbering" %}
{% set version = "0.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: c9607671ac511236fa5d61a7491c1031e700e8d498c9d2418e6c61d1251209ae
  # TODO: remove after https://github.com/executablebooks/sphinx-multitoc-numbering/pull/19
  - url: https://raw.githubusercontent.com/executablebooks/{{ name }}/v{{ version }}/LICENSE
    sha256: 88d2617b6aa5abba082c722476754a0aa17ddc0aa06e2e46f896e4bbb7d25b3d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sphinx >=3

test:
  imports:
    - sphinx_multitoc_numbering
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sphinx-multitoc-numbering
  summary: Supporting continuous HTML section numbering
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-multitoc-numbering.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
